### ISSUE TITLE
Can it deal with ros2 bags as well ? 

### ISSUE THREAD

**Issue by jediofgever** [cruise-automation/rosbag.js#125]
Hi, 

I am wondering whether It is possible to also use ros2 bag files, if not would it be straightforward to extend it?

**Comment by jtbandes** [comment]
Foxglove Studio can load ROS 2 bags (db3 or mcap): https://foxglove.dev/docs/studio/connection/ros2

**Comment by jediofgever** [comment]
But I need API to load and manipulate the contents of the bag file

**Comment by jtbandes** [comment]
You can use https://github.com/foxglove/rosbag2-node or https://github.com/foxglove/rosbag2-web

**Comment by jediofgever** [comment]
many thanks, I think rosbag2-node is suitable, is there any example of the usage ? I couldn’t see it

**Comment by jtbandes** [comment]
Examples in https://github.com/foxglove/rosbag2-node/blob/main/src/Rosbag2.test.ts
