### ISSUE TITLE
How can you detect the end of reading results & other comments!

### ISSUE THREAD

**Issue by gkjohnson** [cruise-automation/rosbag.js#21]
Hello!

First off -- thank you for making your parser available publicly! So far it seems to work fantastically. I'm still just getting started with it but I had a few questions and comments about how to use it. I'm using the currently published npm version 1.2.1, though I see that the structure of the repo has changed a bit since the last publish.

- When reading rosbag data is there a way to detect when the reader has finished returning ReadResults? You could compare the bag `endTime` to the ReadResult `timestamp` to see if they're equal but that doesn't seem like the most robust approach.
- Is there documentation on how to load the library in a browser? Is a build process required? It would be nice to have an example.
- The documentation for "BagOptions" references `https://github.com/cruise-automation/rosbag.js/blob/master/test/rosbag.js#L139`, which is no longer available. Presumably it should point to `rosbag.test.js`.

Thanks again!
Garrett

**Comment by jtbandes** [comment]
Hi, and thanks for your interest!

The `readMessages()` function returns a [Promise](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise) on which you can use `.then()` or `await` to detect when reading is finished. Here's an example using `await` in an async function from the tests, where execution won't continue until the bag has been fully read: https://github.com/cruise-automation/rosbag.js/blob/545529344c8c2a0b3a3126646d065043c2d67d84/src/bag.test.js#L32-L34

As of the latest changes in #20, a build step shouldn't be required if you're making a static page; as I noted in that PR summary, you can simply use `<script src="node_modules/rosbag/dist/web/index.js"></script>` which will expose a `rosbag` object. We haven't published this version to npm yet but I'll do that shortly; thanks for the reminder! (I'll fix the BagOptions docs as well 😃)

**Comment by gkjohnson** [comment]
Great! Thank you so much for the fast response -- I missed the documentation about `readResults` returning a promise. I'll look forward to the next release.
