### ISSUE TITLE
Add BigInt reading support

### ISSUE THREAD

**Issue by jtbandes** [cruise-automation/rosbag.js#28]
Not all values of `int64` and `uint64` types can be represented in plain Numbers in JS. We currently use [int53](https://www.npmjs.com/package/int53) which just logs a `console.assert` error if the number is out of range, but doesn't prevent returning an incorrect value. The new [BigInt](https://developers.google.com/web/updates/2018/05/bigint) type can be used instead, but this should be an opt-in feature because it's not source compatible (for instance, `1n + 2` is a type error).

**Comment by YECHUNAN** [comment]
Is there any updates on this issue? If you haven't started working on it. I might be able to contribute since I have a project running into this problem right now.

**Comment by jtbandes** [comment]
Please check out [`@foxglove/rosbag`](https://github.com/foxglove/rosbag) and [`@foxglove/rosmsg`](https://github.com/foxglove/rosmsg) which suppor bigints natively.
