### ISSUE TITLE
"should read bytes from a file" test fails on Windows

### ISSUE THREAD

**Issue by gkjohnson** [cruise-automation/rosbag.js#31]
The test fails [here](https://github.com/cruise-automation/rosbag.js/blob/master/src/node/index.test.js#L21) on Windows because the reported size is 22 bytes rather than 21 bytes. I'm not exactly sure why but maybe it has something to do with line endings or an added byte at eof when reading?

One option is just to make sure that the reported size is the same as the size reported by the `fs.stat`:
```js
assert.equal(reader.size(), fs.statSync(fixture).size);
```

**Comment by janpaul123** [comment]
Omg, classic windows. `assert.equal(reader.size(), fs.statSync(fixture).size);` seems reasonable to me.

**Comment by jtbandes** [comment]
Can't imagine that it would have to do with line endings, since the Reader is also using stat 😫

https://github.com/cruise-automation/rosbag.js/blob/1ee7dc3b5cd832013f498542a9f490b8765817f5/src/node/index.js#L43

**Comment by janpaul123** [comment]
@jtbandes Yeah but on windows non-binary files are typically converted by git during clone/checkout to windows format which uses two bytes for line endings (cr-lf) instead of one on unix systems (lf). So it would make sense for `stat.size` to also report 22 bytes.

**Comment by gkjohnson** [comment]
Heh, I was screaming on the inside, too.

> `assert.equal(reader.size(), fs.statSync(fixture).size);` seems reasonable to me.

Great -- tacked this onto PR #30
