### ISSUE TITLE
Node.js streams support for .pipe()

### ISSUE THREAD

**Issue by paramaggarwal** [cruise-automation/rosbag.js#37]
Currently `getMessages()` reads all the messages as fast as possible. I have a use case of processing this data and I would like to pause the reading of the bag while I process the messages that are already read. 

By having a stream based API, I will be able to handle the entire processing pipeline as a Node.js stream.

**Comment by janpaul123** [comment]
That seems reasonable to me. cc @jtbandes @brianc

**Comment by brianc** [comment]
Yeah sounds reasonable - what type of API are you thinking?  We'd still likely need the same config object passed to `getMessages` passed to the stream constructor to make it an idiomatic node stream I believe.

For example: 

```js
// bagStream would be in objectMode: true
const bagStream = new RosbagStream({ topics: ['/foo', '/bar'], decompress }) // could support optional startTime & endTime as well

bagStream.pipe(through2(function (message) {

}))
```

**Comment by paramaggarwal** [comment]
Yes, I think that's what the API would look like. Currently it seems to read the entire bag to memory if `readMessages()` is called (without any filter). 

https://github.com/cruise-automation/rosbag.js/blob/28b4c6b9fdced63d7201ba7530e641f076094afa/src/bag.js#L113-L120

which internally does:

https://github.com/cruise-automation/rosbag.js/blob/28b4c6b9fdced63d7201ba7530e641f076094afa/src/BagReader.js#L204-L206

This would change to becoming on demand once we use a NodeStream.
