### ISSUE TITLE
typescript support

### ISSUE THREAD

**Issue by yokyj** [cruise-automation/rosbag.js#38]
would you add a d.ts file to this project?

**Comment by brianc** [comment]
Hey @yokyj thanks for the question!  We could add a `.d.ts` file to this project...but I thought the normal approach was to add type definitions to [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) for projects that aren't written in TypeScript?  If you write the `.d.ts` & submit a pull request we'll happily add it here; just not sure if it should go over on the DefinitelyTyped repo instead?  We don't use TypeScript + rosbag.js currently (a lot of our stuff is written with Flow) so we don't have any resources to maintain the type definitions at the current time, but we are always happy to review & integrate pull requests into the repo & package!

**Comment by kejxu** [comment]
> the normal approach was to add type definitions to [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) for projects that aren't written in TypeScript

+1. TypeScript support should probably be decoupled from the JavaScript source code. Keeping the `.d.ts` file in the same repository might seem handy, but as Brian mentioned, it does not make sense since TypeScript is not part of native JS.

**Comment by naeemy** [comment]
I have created a [pull request](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/55460) to [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped). Please have a look and review the code if possible.

**Comment by naeemy** [comment]
It's available as [npm package](https://www.npmjs.com/package/@types/rosbag)

**Comment by jtbandes** [comment]
FYI the [`@foxglove/rosbag`](https://github.com/foxglove/rosbag) package has full TypeScript support.

**Comment by Stuk** [comment]
Closed in https://github.com/cruise-automation/rosbag.js/pull/118
